# Argrumnets for FROM
ARG PYTHON_VERSION=3.7

# Build dcf-watcher
FROM python:${PYTHON_VERSION}-alpine

RUN apk add --no-cache --virtual .build-deps g++ python3-dev libffi-dev openssl-dev && \
    apk add --no-cache --update python3 && \
    apk add --no-cache --update alpine-sdk && \
    apk del curl --no-cache

ENV GRPC_PYTHON_VERSION 1.23.0
RUN pip3 install grpcio==${GRPC_PYTHON_VERSION} grpcio-tools==${GRPC_PYTHON_VERSION}

RUN mkdir -p /openfx/watcher
WORKDIR /openfx/watcher

COPY . .

RUN pip3 install --upgrade pip setuptools
RUN pip3 install -r requirements.txt
