# Argrumnets for FROM
ARG PYTHON_VERSION=2.7

# Build dcf-watcher
FROM python:${PYTHON_VERSION}-alpine

RUN apk --no-cache add build-base && \
    apk del curl --no-cache

ENV GRPC_PYTHON_VERSION 1.23.0
RUN pip install grpcio==${GRPC_PYTHON_VERSION} grpcio-tools==${GRPC_PYTHON_VERSION}

RUN mkdir -p /openfx/executor
WORKDIR /openfx/executor

COPY . .

RUN pip install -r requirements.txt
