# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fxwatcher_pb2 as fxwatcher__pb2


class FxWatcherStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Call = channel.unary_unary(
        '/pb.FxWatcher/Call',
        request_serializer=fxwatcher__pb2.Request.SerializeToString,
        response_deserializer=fxwatcher__pb2.Reply.FromString,
        )


class FxWatcherServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Call(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FxWatcherServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Call': grpc.unary_unary_rpc_method_handler(
          servicer.Call,
          request_deserializer=fxwatcher__pb2.Request.FromString,
          response_serializer=fxwatcher__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.FxWatcher', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
