// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fxwatcher.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Input                []byte   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Info                 *Info    `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0465f95993dbcaf2, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Request) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type Reply struct {
	Output               string   `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0465f95993dbcaf2, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type Info struct {
	FunctionName         string     `protobuf:"bytes,1,opt,name=FunctionName,proto3" json:"FunctionName,omitempty"`
	Timeout              string     `protobuf:"bytes,2,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Runtime              string     `protobuf:"bytes,3,opt,name=Runtime,proto3" json:"Runtime,omitempty"`
	Limits               *Resources `protobuf:"bytes,4,opt,name=Limits,proto3" json:"Limits,omitempty"`
	Trigger              *Trigger   `protobuf:"bytes,5,opt,name=Trigger,proto3" json:"Trigger,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_0465f95993dbcaf2, []int{2}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *Info) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *Info) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *Info) GetLimits() *Resources {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *Info) GetTrigger() *Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

type Trigger struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Time                 string   `protobuf:"bytes,3,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trigger) Reset()         { *m = Trigger{} }
func (m *Trigger) String() string { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()    {}
func (*Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_0465f95993dbcaf2, []int{3}
}

func (m *Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trigger.Unmarshal(m, b)
}
func (m *Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trigger.Marshal(b, m, deterministic)
}
func (m *Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trigger.Merge(m, src)
}
func (m *Trigger) XXX_Size() int {
	return xxx_messageInfo_Trigger.Size(m)
}
func (m *Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Trigger proto.InternalMessageInfo

func (m *Trigger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Trigger) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Trigger) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type Resources struct {
	Memory               string   `protobuf:"bytes,1,opt,name=Memory,proto3" json:"Memory,omitempty"`
	CPU                  string   `protobuf:"bytes,2,opt,name=CPU,proto3" json:"CPU,omitempty"`
	GPU                  string   `protobuf:"bytes,3,opt,name=GPU,proto3" json:"GPU,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_0465f95993dbcaf2, []int{4}
}

func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (m *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(m, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *Resources) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

func (m *Resources) GetGPU() string {
	if m != nil {
		return m.GPU
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Reply)(nil), "pb.Reply")
	proto.RegisterType((*Info)(nil), "pb.Info")
	proto.RegisterType((*Trigger)(nil), "pb.Trigger")
	proto.RegisterType((*Resources)(nil), "pb.Resources")
}

func init() { proto.RegisterFile("fxwatcher.proto", fileDescriptor_0465f95993dbcaf2) }

var fileDescriptor_0465f95993dbcaf2 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0x5d, 0x6b, 0xf2, 0x30,
	0x14, 0x7e, 0xab, 0x55, 0xdf, 0x1e, 0x1d, 0x1b, 0x87, 0x31, 0xca, 0x18, 0x4c, 0x02, 0x82, 0x37,
	0xf3, 0xc2, 0x5d, 0xef, 0x4a, 0x50, 0x06, 0xfb, 0x90, 0x50, 0xd9, 0xb5, 0x96, 0xe8, 0x02, 0x6d,
	0x93, 0xa5, 0x09, 0xb3, 0xff, 0x69, 0x3f, 0x72, 0xe4, 0xa3, 0x6e, 0xbb, 0x7b, 0xbe, 0x7a, 0xfa,
	0xe4, 0x1c, 0x38, 0xdf, 0x1f, 0x3f, 0xb7, 0x3a, 0x7f, 0x67, 0x6a, 0x26, 0x95, 0xd0, 0x02, 0x3b,
	0x72, 0x47, 0x1e, 0x60, 0x40, 0xd9, 0x87, 0x61, 0xb5, 0xc6, 0x4b, 0xe8, 0xf1, 0x4a, 0x1a, 0x9d,
	0x46, 0xe3, 0x68, 0x3a, 0xa2, 0x9e, 0xe0, 0x0d, 0xc4, 0xbc, 0xda, 0x8b, 0xb4, 0x33, 0x8e, 0xa6,
	0xc3, 0xf9, 0xff, 0x99, 0xdc, 0xcd, 0x1e, 0xab, 0xbd, 0xa0, 0x4e, 0x25, 0xb7, 0xd0, 0xa3, 0x4c,
	0x16, 0x0d, 0x5e, 0x41, 0xff, 0xd5, 0xe8, 0xf6, 0xeb, 0x84, 0x06, 0x46, 0xbe, 0x22, 0x88, 0x6d,
	0x1e, 0x09, 0x8c, 0x96, 0xa6, 0xca, 0x35, 0x17, 0xd5, 0xcb, 0xb6, 0x64, 0x21, 0xf6, 0x47, 0xc3,
	0x14, 0x06, 0x19, 0x2f, 0x99, 0x30, 0xda, 0xfd, 0x2e, 0xa1, 0x2d, 0xb5, 0x0e, 0x35, 0x95, 0xe6,
	0x25, 0x4b, 0xbb, 0xde, 0x09, 0x14, 0x27, 0xd0, 0x7f, 0xe2, 0x25, 0xd7, 0x75, 0x1a, 0xbb, 0x86,
	0x67, 0xb6, 0x21, 0x65, 0xb5, 0x30, 0x2a, 0x67, 0x35, 0x0d, 0x26, 0x4e, 0x60, 0x90, 0x29, 0x7e,
	0x38, 0x30, 0x95, 0xf6, 0x5c, 0x6e, 0x68, 0x73, 0x41, 0xa2, 0xad, 0x47, 0x56, 0xa7, 0x18, 0x22,
	0xc4, 0xbf, 0x8a, 0x3a, 0x6c, 0x57, 0x94, 0x09, 0xc9, 0xf3, 0x50, 0xcf, 0x13, 0x9b, 0xcc, 0x7e,
	0x9a, 0x39, 0x4c, 0x56, 0x90, 0x9c, 0x4a, 0xd8, 0xe5, 0x3c, 0xb3, 0x52, 0xa8, 0xa6, 0x5d, 0x8e,
	0x67, 0x78, 0x01, 0xdd, 0xc5, 0x7a, 0x13, 0x86, 0x59, 0x68, 0x95, 0xd5, 0x7a, 0x13, 0x26, 0x59,
	0x38, 0xbf, 0x83, 0x64, 0x79, 0x7c, 0xf3, 0x77, 0xc3, 0x31, 0xc4, 0x8b, 0x6d, 0x51, 0xe0, 0xd0,
	0x3f, 0xd2, 0xdd, 0xed, 0x3a, 0xf1, 0x44, 0x16, 0x0d, 0xf9, 0xb7, 0xeb, 0xbb, 0xd3, 0xde, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x92, 0xa4, 0xdd, 0xed, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FxWatcherClient is the client API for FxWatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FxWatcherClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type fxWatcherClient struct {
	cc *grpc.ClientConn
}

func NewFxWatcherClient(cc *grpc.ClientConn) FxWatcherClient {
	return &fxWatcherClient{cc}
}

func (c *fxWatcherClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/pb.FxWatcher/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FxWatcherServer is the server API for FxWatcher service.
type FxWatcherServer interface {
	Call(context.Context, *Request) (*Reply, error)
}

// UnimplementedFxWatcherServer can be embedded to have forward compatible implementations.
type UnimplementedFxWatcherServer struct {
}

func (*UnimplementedFxWatcherServer) Call(ctx context.Context, req *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}

func RegisterFxWatcherServer(s *grpc.Server, srv FxWatcherServer) {
	s.RegisterService(&_FxWatcher_serviceDesc, srv)
}

func _FxWatcher_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxWatcherServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxWatcher/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxWatcherServer).Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _FxWatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FxWatcher",
	HandlerType: (*FxWatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _FxWatcher_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fxwatcher.proto",
}
