apiVersion: apps/v1
kind: Deployment
metadata:
  name: fxgateway
  namespace: kubesphere-openfx-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fxgateway
  template:
    metadata:
      labels:
        app: fxgateway
    spec:
      serviceAccountName: fxgateway
        #imagePullSecrets:
        #  - name: regcred
        #nodeName: kubernetes-master 
      containers:
      - name: fxgateway
        image: 10.0.0.255/2020_privatecloud/fxgateway:0.1.0
        imagePullPolicy: Always

        env:
        - name: FUNCTION_NAMESPACE
          value: kubesphere-openfx-fn-system
        - name: IMAGE_PULL_POLICY
          value: "Always"

        ports:
        - containerPort: 10000
          protocol: TCP

        resources:
          requests:
            memory: 250Mi
          limits:
            memory: 250Mi
