---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fxgateway
  namespace: openfx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fxgateway-role 
  namespace: openfx-fn
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fxgateway-fn-access
  namespace: openfx-fn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fxgateway-role
subjects:
- kind: ServiceAccount
  name: fxgateway
  namespace: openfx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fxgateway-clusterrole
  namespace: openfx-fn
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - list
  - get
  - update
  - watch
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - list
  - get
  - update
  - watch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fxgateway-clusterrole
  namespace: openfx-fn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fxgateway-clusterrole
subjects:
- kind: ServiceAccount
  name: fxgateway
  namespace: openfx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-clusterrole
  namespace: openfx-fn
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-clusterrole
  namespace: openfx-fn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storage-clusterrole
subjects:
- kind: ServiceAccount
  name: storage-provisioner
  namespace: kube-system
