# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fxwatcher.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("fxwatcher.proto", :syntax => :proto3) do
    add_message "pb.Request" do
      optional :input, :bytes, 1
      optional :info, :message, 2, "pb.Info"
    end
    add_message "pb.Reply" do
      optional :Output, :string, 1
    end
    add_message "pb.Info" do
      optional :FunctionName, :string, 1
      optional :Timeout, :string, 2
      optional :Runtime, :string, 3
      optional :Limits, :message, 4, "pb.Resources"
      optional :Trigger, :message, 5, "pb.Trigger"
    end
    add_message "pb.Trigger" do
      optional :Name, :string, 1
      optional :Topic, :string, 2
      optional :Time, :string, 3
    end
    add_message "pb.Resources" do
      optional :Memory, :string, 1
      optional :CPU, :string, 2
      optional :GPU, :string, 3
    end
  end
end

module Pb
  Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Request").msgclass
  Reply = Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Reply").msgclass
  Info = Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Info").msgclass
  Trigger = Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Trigger").msgclass
  Resources = Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.Resources").msgclass
end
