// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fxgateway.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Message struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Messages struct {
	Output               []byte   `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Messages) Reset()         { *m = Messages{} }
func (m *Messages) String() string { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()    {}
func (*Messages) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{2}
}
func (m *Messages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Messages.Unmarshal(m, b)
}
func (m *Messages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Messages.Marshal(b, m, deterministic)
}
func (dst *Messages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Messages.Merge(dst, src)
}
func (m *Messages) XXX_Size() int {
	return xxx_messageInfo_Messages.Size(m)
}
func (m *Messages) XXX_DiscardUnknown() {
	xxx_messageInfo_Messages.DiscardUnknown(m)
}

var xxx_messageInfo_Messages proto.InternalMessageInfo

func (m *Messages) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

type TokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{3}
}
func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (dst *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(dst, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateFunctionRequest struct {
	Service              string             `protobuf:"bytes,1,opt,name=Service,proto3" json:"Service,omitempty"`
	Image                string             `protobuf:"bytes,2,opt,name=Image,proto3" json:"Image,omitempty"`
	EnvVars              map[string]string  `protobuf:"bytes,3,rep,name=EnvVars,proto3" json:"EnvVars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Labels               map[string]string  `protobuf:"bytes,4,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Annotations          map[string]string  `protobuf:"bytes,5,rep,name=Annotations,proto3" json:"Annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Constraints          []string           `protobuf:"bytes,6,rep,name=Constraints,proto3" json:"Constraints,omitempty"`
	Secrets              []string           `protobuf:"bytes,7,rep,name=Secrets,proto3" json:"Secrets,omitempty"`
	RegistryAuth         string             `protobuf:"bytes,8,opt,name=RegistryAuth,proto3" json:"RegistryAuth,omitempty"`
	Limits               *FunctionResources `protobuf:"bytes,9,opt,name=Limits,proto3" json:"Limits,omitempty"`
	Requests             *FunctionResources `protobuf:"bytes,10,opt,name=Requests,proto3" json:"Requests,omitempty"`
	MinReplicas          int32              `protobuf:"varint,11,opt,name=MinReplicas,proto3" json:"MinReplicas,omitempty"`
	MaxReplicas          int32              `protobuf:"varint,12,opt,name=MaxReplicas,proto3" json:"MaxReplicas,omitempty"`
	Token                string             `protobuf:"bytes,13,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateFunctionRequest) Reset()         { *m = CreateFunctionRequest{} }
func (m *CreateFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFunctionRequest) ProtoMessage()    {}
func (*CreateFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{4}
}
func (m *CreateFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFunctionRequest.Unmarshal(m, b)
}
func (m *CreateFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFunctionRequest.Marshal(b, m, deterministic)
}
func (dst *CreateFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFunctionRequest.Merge(dst, src)
}
func (m *CreateFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFunctionRequest.Size(m)
}
func (m *CreateFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFunctionRequest proto.InternalMessageInfo

func (m *CreateFunctionRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *CreateFunctionRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *CreateFunctionRequest) GetEnvVars() map[string]string {
	if m != nil {
		return m.EnvVars
	}
	return nil
}

func (m *CreateFunctionRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *CreateFunctionRequest) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *CreateFunctionRequest) GetConstraints() []string {
	if m != nil {
		return m.Constraints
	}
	return nil
}

func (m *CreateFunctionRequest) GetSecrets() []string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *CreateFunctionRequest) GetRegistryAuth() string {
	if m != nil {
		return m.RegistryAuth
	}
	return ""
}

func (m *CreateFunctionRequest) GetLimits() *FunctionResources {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *CreateFunctionRequest) GetRequests() *FunctionResources {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *CreateFunctionRequest) GetMinReplicas() int32 {
	if m != nil {
		return m.MinReplicas
	}
	return 0
}

func (m *CreateFunctionRequest) GetMaxReplicas() int32 {
	if m != nil {
		return m.MaxReplicas
	}
	return 0
}

func (m *CreateFunctionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateNamespaceRequest struct {
	NamespaceName        string   `protobuf:"bytes,1,opt,name=NamespaceName,proto3" json:"NamespaceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceRequest) Reset()         { *m = CreateNamespaceRequest{} }
func (m *CreateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRequest) ProtoMessage()    {}
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{5}
}
func (m *CreateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRequest.Unmarshal(m, b)
}
func (m *CreateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRequest.Marshal(b, m, deterministic)
}
func (dst *CreateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRequest.Merge(dst, src)
}
func (m *CreateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRequest.Size(m)
}
func (m *CreateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRequest proto.InternalMessageInfo

func (m *CreateNamespaceRequest) GetNamespaceName() string {
	if m != nil {
		return m.NamespaceName
	}
	return ""
}

type LoginRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Member               string   `protobuf:"bytes,2,opt,name=Member,proto3" json:"Member,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{6}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginRequest) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

type LoginResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{7}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StartRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{8}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type StartResponse struct {
	IDE                  string   `protobuf:"bytes,1,opt,name=IDE,proto3" json:"IDE,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{9}
}
func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (dst *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(dst, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

func (m *StartResponse) GetIDE() string {
	if m != nil {
		return m.IDE
	}
	return ""
}

type ExitRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitRequest) Reset()         { *m = ExitRequest{} }
func (m *ExitRequest) String() string { return proto.CompactTextString(m) }
func (*ExitRequest) ProtoMessage()    {}
func (*ExitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{10}
}
func (m *ExitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitRequest.Unmarshal(m, b)
}
func (m *ExitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitRequest.Marshal(b, m, deterministic)
}
func (dst *ExitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitRequest.Merge(dst, src)
}
func (m *ExitRequest) XXX_Size() int {
	return xxx_messageInfo_ExitRequest.Size(m)
}
func (m *ExitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExitRequest proto.InternalMessageInfo

func (m *ExitRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ExitResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitResponse) Reset()         { *m = ExitResponse{} }
func (m *ExitResponse) String() string { return proto.CompactTextString(m) }
func (*ExitResponse) ProtoMessage()    {}
func (*ExitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{11}
}
func (m *ExitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitResponse.Unmarshal(m, b)
}
func (m *ExitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitResponse.Marshal(b, m, deterministic)
}
func (dst *ExitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitResponse.Merge(dst, src)
}
func (m *ExitResponse) XXX_Size() int {
	return xxx_messageInfo_ExitResponse.Size(m)
}
func (m *ExitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExitResponse proto.InternalMessageInfo

func (m *ExitResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteFunctionRequest struct {
	FunctionName         string   `protobuf:"bytes,1,opt,name=FunctionName,proto3" json:"FunctionName,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFunctionRequest) Reset()         { *m = DeleteFunctionRequest{} }
func (m *DeleteFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFunctionRequest) ProtoMessage()    {}
func (*DeleteFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{12}
}
func (m *DeleteFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFunctionRequest.Unmarshal(m, b)
}
func (m *DeleteFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFunctionRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFunctionRequest.Merge(dst, src)
}
func (m *DeleteFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFunctionRequest.Size(m)
}
func (m *DeleteFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFunctionRequest proto.InternalMessageInfo

func (m *DeleteFunctionRequest) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *DeleteFunctionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ScaleServiceRequest struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	Replicas             uint64   `protobuf:"varint,2,opt,name=Replicas,proto3" json:"Replicas,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScaleServiceRequest) Reset()         { *m = ScaleServiceRequest{} }
func (m *ScaleServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ScaleServiceRequest) ProtoMessage()    {}
func (*ScaleServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{13}
}
func (m *ScaleServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScaleServiceRequest.Unmarshal(m, b)
}
func (m *ScaleServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScaleServiceRequest.Marshal(b, m, deterministic)
}
func (dst *ScaleServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScaleServiceRequest.Merge(dst, src)
}
func (m *ScaleServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ScaleServiceRequest.Size(m)
}
func (m *ScaleServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScaleServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScaleServiceRequest proto.InternalMessageInfo

func (m *ScaleServiceRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ScaleServiceRequest) GetReplicas() uint64 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *ScaleServiceRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type InvokeServiceRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=Service,proto3" json:"Service,omitempty"`
	Input                []byte   `protobuf:"bytes,2,opt,name=Input,proto3" json:"Input,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeServiceRequest) Reset()         { *m = InvokeServiceRequest{} }
func (m *InvokeServiceRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeServiceRequest) ProtoMessage()    {}
func (*InvokeServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{14}
}
func (m *InvokeServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeServiceRequest.Unmarshal(m, b)
}
func (m *InvokeServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeServiceRequest.Marshal(b, m, deterministic)
}
func (dst *InvokeServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeServiceRequest.Merge(dst, src)
}
func (m *InvokeServiceRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeServiceRequest.Size(m)
}
func (m *InvokeServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeServiceRequest proto.InternalMessageInfo

func (m *InvokeServiceRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *InvokeServiceRequest) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *InvokeServiceRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type FunctionRequest struct {
	FunctionName         string   `protobuf:"bytes,1,opt,name=FunctionName,proto3" json:"FunctionName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionRequest) Reset()         { *m = FunctionRequest{} }
func (m *FunctionRequest) String() string { return proto.CompactTextString(m) }
func (*FunctionRequest) ProtoMessage()    {}
func (*FunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{15}
}
func (m *FunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionRequest.Unmarshal(m, b)
}
func (m *FunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionRequest.Marshal(b, m, deterministic)
}
func (dst *FunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionRequest.Merge(dst, src)
}
func (m *FunctionRequest) XXX_Size() int {
	return xxx_messageInfo_FunctionRequest.Size(m)
}
func (m *FunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionRequest proto.InternalMessageInfo

func (m *FunctionRequest) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

type Functions struct {
	Functions            []*Function `protobuf:"bytes,1,rep,name=Functions,proto3" json:"Functions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Functions) Reset()         { *m = Functions{} }
func (m *Functions) String() string { return proto.CompactTextString(m) }
func (*Functions) ProtoMessage()    {}
func (*Functions) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{16}
}
func (m *Functions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Functions.Unmarshal(m, b)
}
func (m *Functions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Functions.Marshal(b, m, deterministic)
}
func (dst *Functions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Functions.Merge(dst, src)
}
func (m *Functions) XXX_Size() int {
	return xxx_messageInfo_Functions.Size(m)
}
func (m *Functions) XXX_DiscardUnknown() {
	xxx_messageInfo_Functions.DiscardUnknown(m)
}

var xxx_messageInfo_Functions proto.InternalMessageInfo

func (m *Functions) GetFunctions() []*Function {
	if m != nil {
		return m.Functions
	}
	return nil
}

type Function struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Image                string            `protobuf:"bytes,2,opt,name=Image,proto3" json:"Image,omitempty"`
	InvocationCount      uint64            `protobuf:"varint,3,opt,name=InvocationCount,proto3" json:"InvocationCount,omitempty"`
	Replicas             uint64            `protobuf:"varint,4,opt,name=Replicas,proto3" json:"Replicas,omitempty"`
	AvailableReplicas    uint64            `protobuf:"varint,5,opt,name=AvailableReplicas,proto3" json:"AvailableReplicas,omitempty"`
	Annotations          map[string]string `protobuf:"bytes,6,rep,name=Annotations,proto3" json:"Annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Labels               map[string]string `protobuf:"bytes,7,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Function) Reset()         { *m = Function{} }
func (m *Function) String() string { return proto.CompactTextString(m) }
func (*Function) ProtoMessage()    {}
func (*Function) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{17}
}
func (m *Function) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Function.Unmarshal(m, b)
}
func (m *Function) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Function.Marshal(b, m, deterministic)
}
func (dst *Function) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Function.Merge(dst, src)
}
func (m *Function) XXX_Size() int {
	return xxx_messageInfo_Function.Size(m)
}
func (m *Function) XXX_DiscardUnknown() {
	xxx_messageInfo_Function.DiscardUnknown(m)
}

var xxx_messageInfo_Function proto.InternalMessageInfo

func (m *Function) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Function) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Function) GetInvocationCount() uint64 {
	if m != nil {
		return m.InvocationCount
	}
	return 0
}

func (m *Function) GetReplicas() uint64 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *Function) GetAvailableReplicas() uint64 {
	if m != nil {
		return m.AvailableReplicas
	}
	return 0
}

func (m *Function) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *Function) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type FunctionResources struct {
	Memory               string   `protobuf:"bytes,1,opt,name=Memory,proto3" json:"Memory,omitempty"`
	CPU                  string   `protobuf:"bytes,2,opt,name=CPU,proto3" json:"CPU,omitempty"`
	GPU                  string   `protobuf:"bytes,3,opt,name=GPU,proto3" json:"GPU,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionResources) Reset()         { *m = FunctionResources{} }
func (m *FunctionResources) String() string { return proto.CompactTextString(m) }
func (*FunctionResources) ProtoMessage()    {}
func (*FunctionResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxgateway_fe6707bcf4fff741, []int{18}
}
func (m *FunctionResources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionResources.Unmarshal(m, b)
}
func (m *FunctionResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionResources.Marshal(b, m, deterministic)
}
func (dst *FunctionResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionResources.Merge(dst, src)
}
func (m *FunctionResources) XXX_Size() int {
	return xxx_messageInfo_FunctionResources.Size(m)
}
func (m *FunctionResources) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionResources.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionResources proto.InternalMessageInfo

func (m *FunctionResources) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *FunctionResources) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

func (m *FunctionResources) GetGPU() string {
	if m != nil {
		return m.GPU
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*Messages)(nil), "pb.Messages")
	proto.RegisterType((*TokenRequest)(nil), "pb.TokenRequest")
	proto.RegisterType((*CreateFunctionRequest)(nil), "pb.CreateFunctionRequest")
	proto.RegisterMapType((map[string]string)(nil), "pb.CreateFunctionRequest.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.CreateFunctionRequest.EnvVarsEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.CreateFunctionRequest.LabelsEntry")
	proto.RegisterType((*CreateNamespaceRequest)(nil), "pb.CreateNamespaceRequest")
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.LoginResponse")
	proto.RegisterType((*StartRequest)(nil), "pb.StartRequest")
	proto.RegisterType((*StartResponse)(nil), "pb.StartResponse")
	proto.RegisterType((*ExitRequest)(nil), "pb.ExitRequest")
	proto.RegisterType((*ExitResponse)(nil), "pb.ExitResponse")
	proto.RegisterType((*DeleteFunctionRequest)(nil), "pb.DeleteFunctionRequest")
	proto.RegisterType((*ScaleServiceRequest)(nil), "pb.ScaleServiceRequest")
	proto.RegisterType((*InvokeServiceRequest)(nil), "pb.InvokeServiceRequest")
	proto.RegisterType((*FunctionRequest)(nil), "pb.FunctionRequest")
	proto.RegisterType((*Functions)(nil), "pb.Functions")
	proto.RegisterType((*Function)(nil), "pb.Function")
	proto.RegisterMapType((map[string]string)(nil), "pb.Function.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.Function.LabelsEntry")
	proto.RegisterType((*FunctionResources)(nil), "pb.FunctionResources")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FxGatewayClient is the client API for FxGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FxGatewayClient interface {
	Invoke(ctx context.Context, in *InvokeServiceRequest, opts ...grpc.CallOption) (*Message, error)
	Create(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*Message, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	StartIDE(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	ExitIDE(ctx context.Context, in *ExitRequest, opts ...grpc.CallOption) (*ExitResponse, error)
	List(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*Functions, error)
	Deploy(ctx context.Context, in *CreateFunctionRequest, opts ...grpc.CallOption) (*Message, error)
	Delete(ctx context.Context, in *DeleteFunctionRequest, opts ...grpc.CallOption) (*Message, error)
	Update(ctx context.Context, in *CreateFunctionRequest, opts ...grpc.CallOption) (*Message, error)
	GetMeta(ctx context.Context, in *FunctionRequest, opts ...grpc.CallOption) (*Function, error)
	GetLog(ctx context.Context, in *FunctionRequest, opts ...grpc.CallOption) (*Message, error)
	ReplicaUpdate(ctx context.Context, in *ScaleServiceRequest, opts ...grpc.CallOption) (*Message, error)
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Message, error)
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Message, error)
}

type fxGatewayClient struct {
	cc *grpc.ClientConn
}

func NewFxGatewayClient(cc *grpc.ClientConn) FxGatewayClient {
	return &fxGatewayClient{cc}
}

func (c *fxGatewayClient) Invoke(ctx context.Context, in *InvokeServiceRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) Create(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) StartIDE(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/StartIDE", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) ExitIDE(ctx context.Context, in *ExitRequest, opts ...grpc.CallOption) (*ExitResponse, error) {
	out := new(ExitResponse)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/ExitIDE", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) List(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*Functions, error) {
	out := new(Functions)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) Deploy(ctx context.Context, in *CreateFunctionRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/Deploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) Delete(ctx context.Context, in *DeleteFunctionRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) Update(ctx context.Context, in *CreateFunctionRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) GetMeta(ctx context.Context, in *FunctionRequest, opts ...grpc.CallOption) (*Function, error) {
	out := new(Function)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/GetMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) GetLog(ctx context.Context, in *FunctionRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/GetLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) ReplicaUpdate(ctx context.Context, in *ScaleServiceRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/ReplicaUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxGatewayClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/pb.FxGateway/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FxGatewayServer is the server API for FxGateway service.
type FxGatewayServer interface {
	Invoke(context.Context, *InvokeServiceRequest) (*Message, error)
	Create(context.Context, *CreateNamespaceRequest) (*Message, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	StartIDE(context.Context, *StartRequest) (*StartResponse, error)
	ExitIDE(context.Context, *ExitRequest) (*ExitResponse, error)
	List(context.Context, *TokenRequest) (*Functions, error)
	Deploy(context.Context, *CreateFunctionRequest) (*Message, error)
	Delete(context.Context, *DeleteFunctionRequest) (*Message, error)
	Update(context.Context, *CreateFunctionRequest) (*Message, error)
	GetMeta(context.Context, *FunctionRequest) (*Function, error)
	GetLog(context.Context, *FunctionRequest) (*Message, error)
	ReplicaUpdate(context.Context, *ScaleServiceRequest) (*Message, error)
	Info(context.Context, *Empty) (*Message, error)
	HealthCheck(context.Context, *Empty) (*Message, error)
}

func RegisterFxGatewayServer(s *grpc.Server, srv FxGatewayServer) {
	s.RegisterService(&_FxGateway_serviceDesc, srv)
}

func _FxGateway_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).Invoke(ctx, req.(*InvokeServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).Create(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_StartIDE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).StartIDE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/StartIDE",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).StartIDE(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_ExitIDE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).ExitIDE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/ExitIDE",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).ExitIDE(ctx, req.(*ExitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).List(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).Deploy(ctx, req.(*CreateFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).Delete(ctx, req.(*DeleteFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).Update(ctx, req.(*CreateFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/GetMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).GetMeta(ctx, req.(*FunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_GetLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).GetLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/GetLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).GetLog(ctx, req.(*FunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_ReplicaUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).ReplicaUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/ReplicaUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).ReplicaUpdate(ctx, req.(*ScaleServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxGateway_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxGatewayServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxGateway/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxGatewayServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _FxGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FxGateway",
	HandlerType: (*FxGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _FxGateway_Invoke_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _FxGateway_Create_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _FxGateway_Login_Handler,
		},
		{
			MethodName: "StartIDE",
			Handler:    _FxGateway_StartIDE_Handler,
		},
		{
			MethodName: "ExitIDE",
			Handler:    _FxGateway_ExitIDE_Handler,
		},
		{
			MethodName: "List",
			Handler:    _FxGateway_List_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _FxGateway_Deploy_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _FxGateway_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _FxGateway_Update_Handler,
		},
		{
			MethodName: "GetMeta",
			Handler:    _FxGateway_GetMeta_Handler,
		},
		{
			MethodName: "GetLog",
			Handler:    _FxGateway_GetLog_Handler,
		},
		{
			MethodName: "ReplicaUpdate",
			Handler:    _FxGateway_ReplicaUpdate_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _FxGateway_Info_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _FxGateway_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fxgateway.proto",
}

func init() { proto.RegisterFile("fxgateway.proto", fileDescriptor_fxgateway_fe6707bcf4fff741) }

var fileDescriptor_fxgateway_fe6707bcf4fff741 = []byte{
	// 1163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x97, 0xdf, 0x72, 0xdb, 0xc4,
	0x17, 0xc7, 0xc7, 0xff, 0xed, 0x23, 0xfb, 0x17, 0x67, 0xf3, 0xe7, 0x27, 0x54, 0x4a, 0x9d, 0x6d,
	0x02, 0x9e, 0x40, 0x62, 0x08, 0x30, 0x85, 0x0c, 0x6d, 0xc9, 0xd8, 0x6e, 0xea, 0x19, 0x87, 0xb4,
	0x0a, 0x01, 0x66, 0xe0, 0x66, 0xed, 0x6e, 0x1c, 0x4d, 0x64, 0x49, 0x68, 0xd7, 0x21, 0x26, 0xd3,
	0x1b, 0x5e, 0x81, 0x19, 0x5e, 0x85, 0x07, 0xe1, 0x15, 0xb8, 0xe1, 0x2d, 0x98, 0x5d, 0xad, 0xec,
	0x95, 0x63, 0xa7, 0x13, 0x7a, 0xa7, 0x3d, 0x7b, 0xbe, 0x9f, 0x5d, 0x1d, 0x9f, 0xfd, 0x6a, 0x0d,
	0x4b, 0x67, 0x57, 0x03, 0xc2, 0xe9, 0x2f, 0x64, 0xbc, 0x1b, 0x84, 0x3e, 0xf7, 0x51, 0x3a, 0xe8,
	0x59, 0xef, 0x0e, 0x7c, 0x7f, 0xe0, 0xd2, 0x06, 0x09, 0x9c, 0x06, 0xf1, 0x3c, 0x9f, 0x13, 0xee,
	0xf8, 0x1e, 0x8b, 0x32, 0x70, 0x01, 0x72, 0xed, 0x61, 0xc0, 0xc7, 0xf8, 0x1e, 0x14, 0x8e, 0x28,
	0x63, 0x64, 0x40, 0x51, 0x15, 0x32, 0x47, 0x6c, 0x60, 0xa6, 0x6a, 0xa9, 0x7a, 0xc9, 0x16, 0x8f,
	0x18, 0x43, 0x51, 0x4d, 0x32, 0xb4, 0x0e, 0xf9, 0xe3, 0x11, 0x0f, 0x46, 0x5c, 0x26, 0x94, 0x6d,
	0x35, 0xc2, 0x9b, 0x50, 0xfe, 0xd6, 0xbf, 0xa0, 0x9e, 0x4d, 0x7f, 0x1e, 0x51, 0xc6, 0xd1, 0x2a,
	0xe4, 0xb8, 0x18, 0x2b, 0x4e, 0x34, 0xc0, 0xff, 0xe4, 0x60, 0xad, 0x19, 0x52, 0xc2, 0xe9, 0xb3,
	0x91, 0xd7, 0x17, 0x3b, 0x89, 0xf3, 0x4d, 0x28, 0x9c, 0xd0, 0xf0, 0xd2, 0xe9, 0x53, 0xa5, 0x88,
	0x87, 0x82, 0xd4, 0x19, 0x92, 0x01, 0x35, 0xd3, 0x11, 0x49, 0x0e, 0xd0, 0xd7, 0x50, 0x68, 0x7b,
	0x97, 0xdf, 0x91, 0x90, 0x99, 0x99, 0x5a, 0xa6, 0x6e, 0xec, 0xbd, 0xbf, 0x1b, 0xf4, 0x76, 0xe7,
	0xb2, 0x77, 0x55, 0x62, 0xdb, 0xe3, 0xe1, 0xd8, 0x8e, 0x65, 0xe8, 0x31, 0xe4, 0xbb, 0xa4, 0x47,
	0x5d, 0x66, 0x66, 0x25, 0x60, 0x6b, 0x31, 0x20, 0xca, 0x8b, 0xf4, 0x4a, 0x84, 0xba, 0x60, 0x1c,
	0x4c, 0xeb, 0x69, 0xe6, 0x24, 0x63, 0x7b, 0x31, 0x43, 0x4b, 0x8e, 0x40, 0xba, 0x1c, 0xd5, 0xc0,
	0x68, 0xfa, 0x1e, 0xe3, 0x21, 0x71, 0x3c, 0xce, 0xcc, 0x7c, 0x2d, 0x53, 0x2f, 0xd9, 0x7a, 0x28,
	0x2a, 0x50, 0x3f, 0xa4, 0x9c, 0x99, 0x05, 0x39, 0x1b, 0x0f, 0x11, 0x86, 0xb2, 0x4d, 0x07, 0x0e,
	0xe3, 0xe1, 0xf8, 0x60, 0xc4, 0xcf, 0xcd, 0xa2, 0xac, 0x53, 0x22, 0x86, 0x76, 0x20, 0xdf, 0x75,
	0x86, 0x0e, 0x67, 0x66, 0xa9, 0x96, 0xaa, 0x1b, 0x7b, 0x6b, 0x62, 0xa3, 0xd3, 0x2d, 0x32, 0x7f,
	0x14, 0xf6, 0x29, 0xb3, 0x55, 0x12, 0xfa, 0x04, 0x8a, 0x6a, 0xdf, 0xcc, 0x84, 0xdb, 0x04, 0x93,
	0x34, 0xf1, 0x06, 0x47, 0x8e, 0x67, 0xd3, 0xc0, 0x75, 0xfa, 0x84, 0x99, 0x46, 0x2d, 0x55, 0xcf,
	0xd9, 0x7a, 0x48, 0x66, 0x90, 0xab, 0x49, 0x46, 0x59, 0x65, 0x4c, 0x43, 0xd3, 0xa6, 0xa9, 0x68,
	0x4d, 0x63, 0xed, 0x43, 0x59, 0xff, 0x05, 0x45, 0x83, 0x5e, 0xd0, 0x71, 0xdc, 0xa0, 0x17, 0x74,
	0x2c, 0x74, 0x97, 0xc4, 0x1d, 0x4d, 0x5a, 0x44, 0x0e, 0xf6, 0xd3, 0x5f, 0xa4, 0xac, 0x2f, 0xc1,
	0xd0, 0x7e, 0xbc, 0x3b, 0x49, 0x9f, 0x40, 0x75, 0xf6, 0x37, 0xbb, 0x8b, 0x1e, 0x3f, 0x81, 0xf5,
	0xa8, 0x13, 0xbe, 0x21, 0x43, 0xca, 0x02, 0xd2, 0xa7, 0x71, 0xaf, 0x6f, 0x42, 0x65, 0x12, 0x13,
	0x0f, 0x8a, 0x97, 0x0c, 0xe2, 0xaf, 0xa0, 0xdc, 0xf5, 0x07, 0xce, 0xed, 0x27, 0x4a, 0x9c, 0xc7,
	0x23, 0x3a, 0xec, 0xd1, 0x50, 0x6d, 0x40, 0x8d, 0xf0, 0x06, 0x54, 0x94, 0x9a, 0x05, 0xbe, 0xc7,
	0xe6, 0x1d, 0xeb, 0x4d, 0x28, 0x9f, 0x70, 0x12, 0xf2, 0xdb, 0x8f, 0xec, 0x06, 0x54, 0x54, 0xd6,
	0x14, 0xd4, 0x69, 0xb5, 0x63, 0x50, 0xa7, 0xd5, 0xc6, 0x0f, 0xc1, 0x68, 0x5f, 0x39, 0x6f, 0xe0,
	0xd4, 0xa0, 0x1c, 0x25, 0x2d, 0xdc, 0xcf, 0x4b, 0x58, 0x6b, 0x51, 0x97, 0xde, 0xf4, 0x06, 0x0c,
	0xe5, 0x38, 0xa4, 0x95, 0x2b, 0x11, 0x9b, 0x2e, 0x9a, 0xd6, 0x17, 0x75, 0x60, 0xe5, 0xa4, 0x4f,
	0x5c, 0xaa, 0xbc, 0x24, 0x06, 0xd6, 0xc0, 0x50, 0x11, 0x8d, 0xa7, 0x87, 0x90, 0x25, 0x0e, 0x80,
	0x6a, 0x54, 0x41, 0xcc, 0xda, 0xc5, 0x9b, 0x5d, 0x9a, 0xd1, 0x97, 0xfa, 0x09, 0x56, 0x3b, 0xde,
	0xa5, 0x7f, 0x31, 0xbb, 0xd6, 0xed, 0xc6, 0xe6, 0x09, 0x27, 0x4d, 0x4b, 0x27, 0x8d, 0x06, 0x0b,
	0xe8, 0x9f, 0xc3, 0xd2, 0x7f, 0xa8, 0x0a, 0x7e, 0x04, 0xa5, 0x78, 0xcc, 0xd0, 0xb6, 0x36, 0x30,
	0x53, 0xd2, 0xaf, 0xca, 0x89, 0x53, 0x3d, 0x9d, 0xc6, 0x7f, 0x64, 0xa0, 0x18, 0x8f, 0x10, 0x82,
	0xac, 0xb6, 0x42, 0x36, 0xae, 0xf7, 0x1c, 0x57, 0xae, 0xc3, 0x92, 0x28, 0x42, 0x5f, 0x9e, 0x99,
	0xa6, 0x3f, 0xf2, 0xb8, 0x7c, 0x8d, 0xac, 0x3d, 0x1b, 0x4e, 0x14, 0x38, 0x3b, 0x53, 0xe0, 0x8f,
	0x60, 0xf9, 0xe0, 0x92, 0x38, 0x2e, 0xe9, 0xb9, 0x74, 0x92, 0x94, 0x93, 0x49, 0x37, 0x27, 0xd0,
	0xd3, 0xa4, 0x11, 0xe7, 0xe5, 0x8b, 0xdd, 0xd7, 0x5f, 0xec, 0x0d, 0xde, 0xfb, 0xf1, 0xe4, 0x43,
	0x50, 0x90, 0x5a, 0x33, 0xa1, 0x9d, 0xe3, 0xfd, 0x6f, 0x6b, 0x0d, 0x6f, 0xe1, 0x4a, 0xf8, 0x18,
	0x96, 0x6f, 0xb8, 0xb0, 0x32, 0x01, 0x3f, 0x8c, 0x19, 0x6a, 0x24, 0xc0, 0xcd, 0x17, 0xa7, 0x0a,
	0x22, 0x1e, 0x45, 0xe4, 0xf0, 0xc5, 0xa9, 0xea, 0x2d, 0xf1, 0xb8, 0xf7, 0x67, 0x11, 0x4a, 0xcf,
	0xae, 0x0e, 0xa3, 0x8b, 0x03, 0x7a, 0x09, 0xf9, 0xa8, 0x8b, 0x91, 0xac, 0xc2, 0xbc, 0x8e, 0xb6,
	0x0c, 0x31, 0xa3, 0x2e, 0x04, 0xb8, 0xf6, 0xdb, 0x5f, 0x7f, 0xff, 0x9e, 0xb6, 0xf0, 0x9a, 0xbc,
	0x61, 0x38, 0x32, 0xbf, 0x71, 0xad, 0x14, 0xaf, 0xf7, 0x53, 0xdb, 0xe8, 0x47, 0xc8, 0x47, 0x3e,
	0x88, 0xac, 0xe9, 0xd7, 0x71, 0xd6, 0x13, 0x93, 0xd0, 0xba, 0x84, 0x62, 0x7c, 0x5f, 0x42, 0xfb,
	0x52, 0xe1, 0xb1, 0xc6, 0x75, 0xc2, 0x20, 0x25, 0xbc, 0x09, 0x39, 0x69, 0x73, 0xa8, 0x2a, 0xf4,
	0xba, 0x5f, 0x5a, 0xcb, 0x5a, 0x24, 0xf2, 0x1c, 0xbc, 0x26, 0xb9, 0x4b, 0x18, 0x24, 0xd7, 0x15,
	0x73, 0x02, 0x72, 0x0c, 0x45, 0x69, 0x71, 0x9d, 0x56, 0x3b, 0xe2, 0xe8, 0xb6, 0x18, 0x71, 0x12,
	0x16, 0x88, 0xdf, 0x93, 0x1c, 0x13, 0xaf, 0x48, 0x4e, 0x18, 0x25, 0x76, 0x5a, 0xed, 0x9d, 0x53,
	0xbb, 0x2b, 0x80, 0x4f, 0xa1, 0x20, 0xbc, 0x4e, 0xf0, 0x96, 0x84, 0x5a, 0x73, 0x47, 0xab, 0x3a,
	0x0d, 0x28, 0xda, 0xb2, 0xa4, 0x19, 0xb8, 0x24, 0x69, 0xf4, 0xca, 0xe1, 0xe8, 0x31, 0x64, 0xbb,
	0x0e, 0xe3, 0xd1, 0x6e, 0xf4, 0x7b, 0x95, 0x55, 0xd1, 0x9b, 0x93, 0xe1, 0x55, 0xa9, 0xfd, 0x9f,
	0xd2, 0xba, 0x0e, 0xe3, 0x62, 0xfd, 0xe7, 0x90, 0x6f, 0xd1, 0xc0, 0xf5, 0xc7, 0xe8, 0x9d, 0x85,
	0x17, 0x92, 0x64, 0xc5, 0xd7, 0x25, 0xa7, 0x8a, 0x0d, 0xc9, 0x79, 0x25, 0xc5, 0x82, 0xf4, 0xbd,
	0x20, 0x09, 0x4f, 0x8e, 0x48, 0x73, 0xfd, 0x39, 0x49, 0xda, 0x92, 0xa4, 0x07, 0xd8, 0x52, 0x24,
	0x21, 0x68, 0x5c, 0xeb, 0xae, 0xf4, 0x5a, 0x6d, 0xf1, 0x34, 0x78, 0x45, 0x62, 0xf0, 0x9d, 0xb7,
	0x38, 0x92, 0x62, 0x41, 0x3a, 0x85, 0xc2, 0x21, 0xe5, 0x47, 0x94, 0x13, 0xb4, 0x92, 0xbc, 0xa4,
	0x44, 0x90, 0x84, 0xc7, 0xe1, 0x0f, 0x24, 0x65, 0x03, 0x3d, 0x68, 0xb0, 0x31, 0xe3, 0x74, 0xd8,
	0x38, 0x53, 0x33, 0x33, 0x7b, 0x14, 0x6f, 0x7e, 0x48, 0x79, 0xd7, 0x1f, 0xcc, 0xa7, 0x26, 0xb6,
	0xf6, 0xa1, 0x84, 0x6e, 0xa1, 0x87, 0xb3, 0xd0, 0x1d, 0xd7, 0x1f, 0xcc, 0x82, 0x7f, 0x80, 0x8a,
	0xf2, 0x2e, 0x55, 0x80, 0xff, 0xcb, 0x06, 0xbb, 0xf9, 0x99, 0x4a, 0xae, 0xb1, 0x21, 0xd7, 0xb8,
	0x67, 0xad, 0xc7, 0x6b, 0x30, 0xa1, 0xd8, 0x89, 0x57, 0x12, 0x95, 0xf8, 0x0c, 0xb2, 0x1d, 0xef,
	0xcc, 0x47, 0x25, 0xd9, 0x62, 0xe2, 0x5e, 0x9f, 0x44, 0xa8, 0x66, 0x41, 0xe5, 0x18, 0xe1, 0x88,
	0xec, 0x47, 0x60, 0x3c, 0xa7, 0xc4, 0xe5, 0xe7, 0xcd, 0x73, 0xda, 0xbf, 0x58, 0x28, 0xae, 0x4a,
	0x31, 0xa0, 0x62, 0xe3, 0x5c, 0x66, 0xff, 0xda, 0xcb, 0xcb, 0xff, 0x10, 0x9f, 0xfe, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x61, 0x74, 0x76, 0x0f, 0x78, 0x0c, 0x00, 0x00,
}
