// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fxwatcher.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Input                []byte   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Info                 *Info    `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxwatcher_b14dfce3c214aa37, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Request) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type Response struct {
	Output               []byte   `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxwatcher_b14dfce3c214aa37, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOutput() []byte {
	if m != nil {
		return m.Output
	}
	return nil
}

type Reply struct {
	Output               string   `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxwatcher_b14dfce3c214aa37, []int{2}
}
func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (dst *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(dst, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type Info struct {
	FunctionName         string     `protobuf:"bytes,1,opt,name=FunctionName,proto3" json:"FunctionName,omitempty"`
	Timeout              string     `protobuf:"bytes,2,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Runtime              string     `protobuf:"bytes,3,opt,name=Runtime,proto3" json:"Runtime,omitempty"`
	Limits               *Resources `protobuf:"bytes,4,opt,name=Limits,proto3" json:"Limits,omitempty"`
	Trigger              *Trigger   `protobuf:"bytes,5,opt,name=Trigger,proto3" json:"Trigger,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxwatcher_b14dfce3c214aa37, []int{3}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (dst *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(dst, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *Info) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *Info) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *Info) GetLimits() *Resources {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *Info) GetTrigger() *Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

type Trigger struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Time                 string   `protobuf:"bytes,3,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trigger) Reset()         { *m = Trigger{} }
func (m *Trigger) String() string { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()    {}
func (*Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxwatcher_b14dfce3c214aa37, []int{4}
}
func (m *Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trigger.Unmarshal(m, b)
}
func (m *Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trigger.Marshal(b, m, deterministic)
}
func (dst *Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trigger.Merge(dst, src)
}
func (m *Trigger) XXX_Size() int {
	return xxx_messageInfo_Trigger.Size(m)
}
func (m *Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Trigger proto.InternalMessageInfo

func (m *Trigger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Trigger) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Trigger) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type Resources struct {
	Memory               string   `protobuf:"bytes,1,opt,name=Memory,proto3" json:"Memory,omitempty"`
	CPU                  string   `protobuf:"bytes,2,opt,name=CPU,proto3" json:"CPU,omitempty"`
	GPU                  string   `protobuf:"bytes,3,opt,name=GPU,proto3" json:"GPU,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_fxwatcher_b14dfce3c214aa37, []int{5}
}
func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (dst *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(dst, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *Resources) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

func (m *Resources) GetGPU() string {
	if m != nil {
		return m.GPU
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*Reply)(nil), "pb.Reply")
	proto.RegisterType((*Info)(nil), "pb.Info")
	proto.RegisterType((*Trigger)(nil), "pb.Trigger")
	proto.RegisterType((*Resources)(nil), "pb.Resources")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FxWatcherClient is the client API for FxWatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FxWatcherClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
	Calls(ctx context.Context, opts ...grpc.CallOption) (FxWatcher_CallsClient, error)
}

type fxWatcherClient struct {
	cc *grpc.ClientConn
}

func NewFxWatcherClient(cc *grpc.ClientConn) FxWatcherClient {
	return &fxWatcherClient{cc}
}

func (c *fxWatcherClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/pb.FxWatcher/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fxWatcherClient) Calls(ctx context.Context, opts ...grpc.CallOption) (FxWatcher_CallsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FxWatcher_serviceDesc.Streams[0], "/pb.FxWatcher/Calls", opts...)
	if err != nil {
		return nil, err
	}
	x := &fxWatcherCallsClient{stream}
	return x, nil
}

type FxWatcher_CallsClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type fxWatcherCallsClient struct {
	grpc.ClientStream
}

func (x *fxWatcherCallsClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fxWatcherCallsClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FxWatcherServer is the server API for FxWatcher service.
type FxWatcherServer interface {
	Call(context.Context, *Request) (*Reply, error)
	Calls(FxWatcher_CallsServer) error
}

func RegisterFxWatcherServer(s *grpc.Server, srv FxWatcherServer) {
	s.RegisterService(&_FxWatcher_serviceDesc, srv)
}

func _FxWatcher_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FxWatcherServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FxWatcher/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FxWatcherServer).Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _FxWatcher_Calls_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FxWatcherServer).Calls(&fxWatcherCallsServer{stream})
}

type FxWatcher_CallsServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type fxWatcherCallsServer struct {
	grpc.ServerStream
}

func (x *fxWatcherCallsServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fxWatcherCallsServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FxWatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FxWatcher",
	HandlerType: (*FxWatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _FxWatcher_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Calls",
			Handler:       _FxWatcher_Calls_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fxwatcher.proto",
}

func init() { proto.RegisterFile("fxwatcher.proto", fileDescriptor_fxwatcher_b14dfce3c214aa37) }

var fileDescriptor_fxwatcher_b14dfce3c214aa37 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x5f, 0x6b, 0xea, 0x40,
	0x10, 0xc5, 0x8d, 0x26, 0x6a, 0x46, 0x2f, 0xf7, 0x32, 0x5c, 0x2e, 0xe1, 0x52, 0xa8, 0x2c, 0x08,
	0x79, 0x92, 0x62, 0x9f, 0xfb, 0x24, 0x28, 0x85, 0xfe, 0x91, 0x25, 0xe2, 0xb3, 0x86, 0xd5, 0x2e,
	0x24, 0xd9, 0x6d, 0xb2, 0x4b, 0xf5, 0x3b, 0xf5, 0x43, 0x96, 0xfd, 0xa3, 0xd6, 0xbe, 0xcd, 0x99,
	0xf9, 0x31, 0x9c, 0x3d, 0xb3, 0xf0, 0x7b, 0x77, 0xf8, 0xd8, 0xa8, 0xfc, 0x8d, 0xd5, 0x13, 0x59,
	0x0b, 0x25, 0xb0, 0x2d, 0xb7, 0xe4, 0x01, 0x7a, 0x94, 0xbd, 0x6b, 0xd6, 0x28, 0xfc, 0x0b, 0x11,
	0xaf, 0xa4, 0x56, 0x49, 0x30, 0x0a, 0xd2, 0x21, 0x75, 0x02, 0x6f, 0x20, 0xe4, 0xd5, 0x4e, 0x24,
	0xed, 0x51, 0x90, 0x0e, 0xa6, 0xfd, 0x89, 0xdc, 0x4e, 0x1e, 0xab, 0x9d, 0xa0, 0xb6, 0x4b, 0x08,
	0xf4, 0x29, 0x6b, 0xa4, 0xa8, 0x1a, 0x86, 0xff, 0xa0, 0xfb, 0xaa, 0xd5, 0x65, 0x81, 0x57, 0xe4,
	0x16, 0x22, 0xca, 0x64, 0x71, 0xfc, 0x01, 0xc4, 0x67, 0xe0, 0x33, 0x80, 0xd0, 0xec, 0x44, 0x02,
	0xc3, 0xb9, 0xae, 0x72, 0xc5, 0x45, 0xf5, 0xb2, 0x29, 0x99, 0xc7, 0xae, 0x7a, 0x98, 0x40, 0x2f,
	0xe3, 0x25, 0x13, 0x5a, 0x59, 0x4b, 0x31, 0x3d, 0x49, 0x33, 0xa1, 0xba, 0x52, 0xbc, 0x64, 0x49,
	0xc7, 0x4d, 0xbc, 0xc4, 0x31, 0x74, 0x9f, 0x78, 0xc9, 0x55, 0x93, 0x84, 0xf6, 0x15, 0xbf, 0xcc,
	0x2b, 0x28, 0x6b, 0x84, 0xae, 0x73, 0xd6, 0x50, 0x3f, 0xc4, 0x31, 0xf4, 0xb2, 0x9a, 0xef, 0xf7,
	0xac, 0x4e, 0x22, 0xcb, 0x0d, 0x0c, 0xe7, 0x5b, 0xf4, 0x34, 0x23, 0x8b, 0x33, 0x86, 0x08, 0xe1,
	0x37, 0xa3, 0xb6, 0x36, 0x31, 0x66, 0x42, 0xf2, 0xdc, 0xdb, 0x73, 0xc2, 0x90, 0xd9, 0xc5, 0x99,
	0xad, 0xc9, 0x02, 0xe2, 0xb3, 0x09, 0x13, 0xce, 0x33, 0x2b, 0x45, 0x7d, 0x3c, 0x85, 0xe3, 0x14,
	0xfe, 0x81, 0xce, 0x6c, 0xb9, 0xf2, 0xcb, 0x4c, 0x69, 0x3a, 0x8b, 0xe5, 0xca, 0x6f, 0x32, 0xe5,
	0x74, 0x0d, 0xf1, 0xfc, 0xb0, 0x76, 0xb7, 0xc5, 0x11, 0x84, 0xb3, 0x4d, 0x51, 0xe0, 0xc0, 0x3d,
	0xd2, 0xde, 0xf6, 0x7f, 0xec, 0x84, 0x2c, 0x8e, 0xa4, 0x85, 0x29, 0x44, 0x86, 0x68, 0xae, 0x91,
	0xa1, 0x0f, 0xc5, 0x1e, 0x93, 0xb4, 0xd2, 0xe0, 0x2e, 0xd8, 0x76, 0xed, 0x47, 0xb9, 0xff, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0x8b, 0x25, 0x98, 0xd6, 0x3b, 0x02, 0x00, 0x00,
}
